import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<string, Record<string, string>> = {
  'en': {
    'welcome': 'Welcome',
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'logout': 'Logout',
    'profile': 'Profile',
    'orders': 'Orders',
    'favorites': 'Favorites',
    'addresses': 'Addresses',
    'payment_methods': 'Payment Methods',
    'notifications': 'Notifications',
    'admin_panel': 'Admin Panel',
    'restaurants': 'Restaurants',
    'foods': 'Foods',
    'search': 'Search',
    'view_restaurant': 'View Restaurant',
    'view_all': 'View All',
    'favorite_foods': 'Favorite Foods',
    'special_offers': 'Special Offers',
    'fast_foods': 'Fast Foods',
    'discounted_foods': 'Discounted Foods',
    'popular_categories': 'Popular Categories',
    'featured_restaurants': 'Featured Restaurants',
    'why_choose_us': 'Why Choose Us?',
    'fast_delivery': 'Fast Delivery',
    'top_restaurants': 'Top Restaurants',
    'real_time_tracking': 'Real-time Tracking',
    'orders_delivered': 'Orders Delivered',
    'average_rating': 'Average Rating',
    'search_placeholder': 'Search for restaurants or cuisines...',
    'delicious_food_title': 'Delicious Food,\nDelivered to Your Door',
    'delicious_food_subtitle': 'Order from the best local restaurants with easy online ordering and fast delivery',
    'craving_special_title': 'Craving Something Special?\nWe\'ve Got You Covered',
    'craving_special_subtitle': 'Discover new flavors and cuisines from top-rated restaurants in your area',
    'fast_fresh_title': 'Fast & Fresh\nEvery Time',
    'fast_fresh_subtitle': 'Hot meals delivered in 30 minutes or less with real-time tracking',
    'fast_delivery_desc': 'Get your food delivered in 30 minutes or less',
    'top_restaurants_desc': 'Order from the best-rated restaurants in your area',
    'real_time_tracking_desc': 'Track your order from kitchen to doorstep',
    'restaurants_discover': 'Discover amazing restaurants and cuisines in your area',
    'search_restaurants': 'Search restaurants...',
    'all_categories': 'All Categories',
    'highest_rated': 'Highest Rated',
    'fastest_delivery': 'Fastest Delivery',
    'lowest_delivery_fee': 'Lowest Delivery Fee',
    'no_restaurants_found': 'No restaurants found',
    'restaurant_found': '{count} restaurant{plural} found',
    'search_results': 'Search Results',
    'filters': 'Filters',
    'sorted_by': 'Sorted by',
    'clear_all': 'Clear all',
    'restaurants_found': '{count} restaurant{plural} found',
    'foods_found': '{count} food item{plural} found',
    'no_foods_found': 'No food items found',
    'search_prompt': 'Enter a search term to find restaurants and foods',
    'language': 'Language',
    'email': 'Email',
    'email_placeholder': 'you@example.com',
    'password': 'Password',
    'password_placeholder': '••••••••',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'signing_in': 'Signing In...',
    'or_continue_with': 'Or continue with',
    'dont_have_account': 'Don\'t have an account?',
    'sign_in_description': 'Sign in to your FoodDash account',
    'login_success': 'You have been successfully logged in.',
    'login_failed': 'Login failed',
    'invalid_credentials': 'Invalid email or password',
    'username': 'Username',
    'username_placeholder': 'Your name',
    'verification_code': 'Verification Code',
    'enter_verification_code': 'Enter verification code',
    'enter_4_digit_code': 'Enter the 4-digit code sent to your email',
    'send_verification_code': 'Send Verification Code',
    'confirm_password': 'Confirm Password',
    'confirm_password_placeholder': 'Confirm your password',
    'creating_account': 'Creating Account...',
    'create_account': 'Create Account',
    'already_have_account': 'Already have an account?',
    'join_fooddash_today': 'Join FoodDash today',
    'verification_code_sent': 'Verification code sent',
    'check_email_for_code': 'Check your email for the 4-digit code',
    'error': 'Error',
    'failed_to_send_verification_code': 'Failed to send verification code',
    'passwords_do_not_match': 'Passwords do not match',
    'password_too_short': 'Password too short',
    'password_min_length': 'Password must be at least 6 characters',
    'invalid_verification_code': 'Invalid verification code',
    'account_created': 'Account created!',
    'welcome_to_fooddash': 'Welcome to FoodDash!',
    'registration_failed': 'Registration failed',
    'settings': 'Settings',
    'quick_links': 'Quick Links',
    'track_order': 'Track Order',
    'new_arrivals': 'New Arrivals',
    'customer_service': 'Customer Service',
    'help_center': 'Help Center',
    'contact_us': 'Contact Us',
    'terms_of_service': 'Terms of Service',
    'privacy_policy': 'Privacy Policy',
    'refund_policy': 'Refund Policy',
    'for_restaurants': 'For Restaurants',
    'partner_with_us': 'Partner With Us',
    'add_your_restaurant': 'Add Your Restaurant',
    'business_blog': 'Business Blog',
    'restaurant_apps': 'Restaurant Apps',
    'delivery_guarantee': '30-min delivery guarantee',
    'secure_payments': 'Secure Payments',
    'pci_compliant': 'PCI compliant payments',
    'daily_offers': 'Daily Offers',
    'exclusive_discounts': 'Exclusive discounts daily',
    'multiple_payment': 'Multiple Payment',
    'all_major_cards': 'All major cards accepted',
    'footer_description': 'Delicious food delivered to your door. Fast, easy, and reliable.',
    'address_kabul': 'Street 123, Kabul, Afghanistan',
    'operating_hours': 'Daily 9:00 AM - 11:00 PM',
    'send_feedback': 'Send Feedback',
    'feedback_description': 'We\'d love to hear from you! Share your thoughts and suggestions.',
    'your_name': 'Your Name',
    'your_email': 'Your Email',
    'your_message': 'Your Message',
    'all_rights_reserved': 'All rights reserved.',
    'designed_with_love': 'Designed with ❤️ in Afghanistan',
    // Add more translations as needed
  },
  'ps': {
    'welcome': 'ښه راغلاست',
    'sign_in': 'ننوزل',
    'sign_up': 'ثبت نام',
    'logout': 'وتل',
    'profile': 'پروفایل',
    'orders': 'اوردرونه',
    'favorites': 'اخواړې',
    'addresses': 'پته',
    'payment_methods': 'د تادیې طریقې',
    'notifications': 'خبرتیاوې',
    'admin_panel': 'مدیریت پانل',
    'restaurants': 'رستورانتونه',
    'foods': 'خواړې',
    'search': 'لټون',
    'view_restaurant': 'رستوران وګورئ',
    'view_all': 'ټول لیدل',
    'favorite_foods': 'اخواړې',
    'special_offers': 'ځانګړې وړاندې',
    'fast_foods': 'چټکې خواړې',
    'discounted_foods': 'تخفیف شوې خواړې',
    'popular_categories': 'مشهورې کټګوري',
    'featured_restaurants': 'ځانګړي رستورانتونه',
    'why_choose_us': 'زموږ انتخاب کولو سبب',
    'fast_delivery': 'چټک تحویل',
    'top_restaurants': 'غوره رستورانتونه',
    'real_time_tracking': 'اوسنۍ معلومات',
    'orders_delivered': 'اوردرونه تحویل شوې',
    'average_rating': 'اوسط درجه بندی',
    'search_placeholder': 'د رستورانتونو یا خواړو لټون ...',
    'delicious_food_title': 'خوږ خواړې،\nتاسو ته تحویل',
    'delicious_food_subtitle': 'د ښه محلي رستورانتونو څخه اسان آنلاین اورډر او چټک تحویل',
    'craving_special_title': 'آیا تاسو یو ځانګړي څه غواړئ؟\nموږ یې تاسو لپاره لرو',
    'craving_special_subtitle': 'په خپلې سیمه کې د غوره درجه بندي شوي رستورانتونو څخه نوي ذائقه او خواړې وپېژئ',
    'fast_fresh_title': 'چټک او تازه\nهر وخت',
    'fast_fresh_subtitle': 'گرم خواړې ۳۰ دقیقو یا کمې تحویل شوې له دوی سره د وخت په واقعیت ټریک کول',
    'fast_delivery_desc': 'ستاسو خواړې ۳۰ دقیقو یا کمې تحویل کړئ',
    'top_restaurants_desc': 'په خپلې سیمه کې څخه غوره درجه بندي شوي رستورانتونو څخه اورډر وکړئ',
    'real_time_tracking_desc': 'د خپلې اورډر څخه د خواړو تیارولو تر دوی تر تحویل یې تعقیب کړئ',
    'restaurants_discover': 'په خپلې سیمه کې د ښه رستورانتونو او خواړو دریابول',
    'search_restaurants': 'د رستورانتونو لټون ...',
    'all_categories': 'ټولې کټګورۍ',
    'highest_rated': 'لوړ درجه بندي شوې',
    'fastest_delivery': 'چټک تحویل',
    'lowest_delivery_fee': 'لږ تر لږه تحویل مصاریف',
    'no_restaurants_found': 'هیڅ رستورانت ونه موندل شو',
    'search_results': 'د لټون پایلې',
    'filters': 'فلټرونه',
    'sorted_by': 'مرتب شوی د',
    'clear_all': 'ټول پاک کړئ',
    'restaurants_found': '{count} رستورانتونه ونه موندل شو',
    'foods_found': '{count} خواړې ونه موندل شو',
    'no_foods_found': 'هیڅ خواړه ونه موندل شوه',
    'search_prompt': 'د رستورانتونو او خواړو لټون لپاره یو لټون کلمه داخل کړئ',
    'language': 'ژبه',
    'email': 'بریښنالیک',
    'email_placeholder': 'تاسو@example.com',
    'password': 'رمز',
    'password_placeholder': '••••••••',
    'remember_me': 'ما په یاد ولره',
    'forgot_password': 'رمز مو هیر شوی؟',
    'signing_in': 'ننوزل...',
    'or_continue_with': 'یا دوام وکړئ د',
    'dont_have_account': 'حساب نلرئ؟',
    'sign_in_description': 'خپل د FoodDash حساب ته ننوځئ',
    'login_success': 'تاسو په بریالیتوب سره ننوتلی یاست.',
    'login_failed': 'ننوزل شکست خورید',
    'invalid_credentials': 'ناسم بريښنالیک یا رمز',
    'username': 'کاربر نوم',
    'username_placeholder': 'ستاسو نوم',
    'verification_code': 'د تایید کود',
    'enter_verification_code': 'د تایید کود داخل کړئ',
    'enter_4_digit_code': 'هغه ۴ رقمی کود چې تاسو ته په بریښنالیک ولیږل شوی',
    'send_verification_code': 'د تایید کود ولیږئ',
    'confirm_password': 'رمز تایید کړئ',
    'confirm_password_placeholder': 'خپل رمز تایید کړئ',
    'creating_account': 'حساب جوړول...',
    'create_account': 'حساب جوړ کړئ',
    'already_have_account': 'حساب لرئ؟',
    'join_fooddash_today': 'نن ورځ FoodDash سره یوځئ',
    'verification_code_sent': 'د تایید کود ولیږل شو',
    'check_email_for_code': 'هغه ۴ رقمی کود چې تاسو ته په بریښنالیک ولیږل شوی',
    'error': 'تېروتنه',
    'failed_to_send_verification_code': 'د تایید کود لیږل شکست خورید',
    'passwords_do_not_match': 'رمزونه سمون نه خوري',
    'password_too_short': 'رمز ډیر لنډ دی',
    'password_min_length': 'رمز باید لږ تر لږه ۶ حرفونه ولري',
    'invalid_verification_code': 'ناسم د تایید کود',
    'account_created': 'حساب جوړ شو!',
    'welcome_to_fooddash': 'ښه راغلاست FoodDash ته!',
    'registration_failed': 'د ثبت نام شکست خورید',
    'settings': 'ترتیبات',
    'quick_links': 'چټکې لینکونه',
    'track_order': 'د اورډر تعقیب',
    'new_arrivals': 'نوی راغلی',
    'customer_service': 'د مشتری خدمتونه',
    'help_center': 'مرکز پورې کړئ',
    'contact_us': 'موږ سره اړیکه ونیسئ',
    'terms_of_service': 'د خدمت شرایط',
    'privacy_policy': 'د پټنتيا تګلاره',
    'refund_policy': 'د بیرته ورکولو تګلاره',
    'for_restaurants': 'د رستورانتونو لپاره',
    'partner_with_us': 'زموږ سره شریک شئ',
    'add_your_restaurant': 'خپل رستورانت اضافه کړئ',
    'business_blog': 'ビジネス بلاګ',
    'restaurant_apps': 'د رستورانت ایپونه',
    'delivery_guarantee': 'د ۳۰ دقیقو تحویل تضمین',
    'secure_payments': 'خوندي تادیې',
    'pci_compliant': 'د PCI تادیې',
    'daily_offers': 'ورځني وړاندې',
    'exclusive_discounts': 'د ورځې لپاره اخص تخفیفونه',
    'multiple_payment': 'ګڼې تادیې',
    'all_major_cards': 'د ټولو مهمو کارتونو تادیه',
    'footer_description': 'خوږ خواړې ستاسو ته تحویل. چټک، اسان، او باورلودلړ.',
    'address_kabul': 'کابل، افغانستان',
    'operating_hours': 'هر ورځ ۹:۰۰ AM - ۱۱:۰۰ PM',
    'send_feedback': 'نظر ولیږئ',
    'feedback_description': 'موږ یې غواړو چې تاسو څخه ویې اوریدل شي! خپل نظرونه او وړاندیزونه شریک کړئ.',
    'your_name': 'ستاسو نوم',
    'your_email': 'ستاسو بریښنالیک',
    'your_message': 'ستاسو پیغام',
    'all_rights_reserved': 'ټول حقونه خوندي دي.',
    'designed_with_love': 'د ❤️ سره په افغانستان کې ډیزاین شوی',
    'my_profile': 'زما پروفایل',
    'manage_delivery_locations': 'د تحویل ځایونه اداره کړئ',
    'manage_payment_options': 'د تادیې اختیارونه اداره کړئ',
    'manage_alerts_updates': 'د خبرتیاوو او تازه معلوماتونو اداره کړئ',
    'saved_addresses': 'خوندي شوي پته',
    'add_address': 'پته اضافه کړئ',
    'no_saved_addresses': 'هیڅ پته نه ده خوندي شوې',
    'add_first_address': 'لومړۍ پته اضافه کړئ',
    'default': 'اصلي',
    'set_default': 'اصلي تنظیم کړئ',
    'delete': 'حذف کړئ',
    'confirm_delete_address': 'آیا تاسو یقین لرئ چې دا پته حذف کړئ؟',
    'address_deleted': 'پته حذف شوه',
    'error_deleting_address': 'د پته حذف کولو کې ستونزه',
    'default_address_updated': 'اصلي پته تازه شوه',
    'error_updating_default_address': 'د اصلي پته تازه کولو کې ستونزه',
    'sending': 'لیږل کیږي...',
    // Add more translations as needed
  },
  'fa': {
    'welcome': 'خوش آمدید',
    'sign_in': 'ورود',
    'sign_up': 'ثبت نام',
    'logout': 'خروج',
    'profile': 'پروفایل',
    'orders': 'سفارشات',
    'favorites': 'علاقه مندی ها',
    'addresses': 'آدرس ها',
    'payment_methods': 'روش های پرداخت',
    'notifications': 'اعلانات',
    'admin_panel': 'پنل مدیریت',
    'restaurants': 'رستوران ها',
    'foods': 'غذاها',
    'search': 'جستجو',
    'view_restaurant': 'مشاهده رستوران',
    'view_all': 'مشاهده همه',
    'favorite_foods': 'غذاهای مورد علاقه',
    'special_offers': 'پیشنهادات ویژه',
    'fast_foods': 'فست فودها',
    'discounted_foods': 'غذاهای تخفیف خورده',
    'popular_categories': 'دسته بندی های محبوب',
    'featured_restaurants': 'رستوران های ویژه',
    'why_choose_us': 'چرا ما را انتخاب کنید؟',
    'fast_delivery': 'تحویل سریع',
    'top_restaurants': 'بهترین رستوران ها',
    'real_time_tracking': 'ردیابی زمان واقعی',
    'orders_delivered': 'سفارشات تحویل داده شده',
    'average_rating': 'میانگین امتیاز',
    'search_placeholder': 'جستجوی رستوران ها یا غذاها...',
    'delicious_food_title': 'غذاهای خوشمزه،\nتحویل درب منزل',
    'delicious_food_subtitle': 'سفارش از بهترین رستوران های محلی با سفارش آنلاین آسان و تحویل سریع',
    'craving_special_title': 'آیا به دنبال چیز خاصی هستید؟\nما همه چیز را برایتان داریم',
    'craving_special_subtitle': 'طعم ها و غذاهای جدید را از رستوران های با امتیاز بالا در منطقه خود کشف کنید',
    'fast_fresh_title': 'سریع و تازه\nهمیشه',
    'fast_fresh_subtitle': 'غذاهای گرم در کمتر از ۳۰ دقیقه تحویل داده شده با ردیابی زمان واقعی',
    'fast_delivery_desc': 'در کمتر از ۳۰ دقیقه غذای خود را تحویل بگیرید',
    'top_restaurants_desc': 'از رستوران های با امتیاز بالا در منطقه خود سفارش دهید',
    'real_time_tracking_desc': 'سفارش خود را از آشپزخانه تا آستانه درب منزل ردیابی کنید',
    'restaurants_discover': 'رستوران ها و غذاهای عالی در منطقه خود را کشف کنید',
    'search_restaurants': 'جستجوی رستوران ها...',
    'all_categories': 'همه دسته بندی ها',
    'highest_rated': 'بالاترین امتیاز',
    'fastest_delivery': 'سریع ترین تحویل',
    'lowest_delivery_fee': 'کمترین هزینه تحویل',
    'no_restaurants_found': 'هیچ رستورانی یافت نشد',
    'search_results': 'نتایج جستجو',
    'filters': 'فیلترها',
    'sorted_by': 'مرتب شده بر اساس',
    'clear_all': 'پاک کردن همه',
    'restaurants_found': '{count} رستوران یافت شد',
    'foods_found': '{count} غذا یافت شد',
    'no_foods_found': 'هیچ غذایی یافت نشد',
    'search_prompt': 'برای یافتن رستوران ها و غذاها یک عبارت جستجو وارد کنید',
    'language': 'زبان',
    'email': 'ایمیل',
    'email_placeholder': 'شما@example.com',
    'password': 'رمز عبور',
    'password_placeholder': '••••••••',
    'remember_me': 'مرا به خاطر بسپار',
    'forgot_password': 'رمز عبور را فراموش کرده اید؟',
    'signing_in': 'در حال ورود...',
    'or_continue_with': 'یا ادامه با',
    'dont_have_account': 'حساب کاربری ندارید؟',
    'sign_in_description': 'وارد حساب FoodDash خود شوید',
    'login_success': 'شما با موفقیت وارد شدید.',
    'login_failed': 'ورود ناموفق',
    'invalid_credentials': 'ایمیل یا رمز عبور نامعتبر',
    'username': 'نام کاربری',
    'username_placeholder': 'نام شما',
    'verification_code': 'کد تأیید',
    'enter_verification_code': 'کد تأیید را وارد کنید',
    'enter_4_digit_code': 'کد ۴ رقمی ارسال شده به ایمیل خود را وارد کنید',
    'send_verification_code': 'ارسال کد تأیید',
    'confirm_password': 'تأیید رمز عبور',
    'confirm_password_placeholder': 'رمز عبور خود را تأیید کنید',
    'creating_account': 'در حال ایجاد حساب...',
    'create_account': 'ایجاد حساب',
    'already_have_account': 'قبلاً حساب کاربری دارید؟',
    'join_fooddash_today': 'امروز به FoodDash بپیوندید',
    'verification_code_sent': 'کد تأیید ارسال شد',
    'check_email_for_code': 'کد ۴ رقمی ارسال شده به ایمیل خود را بررسی کنید',
    'error': 'خطا',
    'failed_to_send_verification_code': 'ارسال کد تأیید ناموفق بود',
    'passwords_do_not_match': 'رمزهای عبور مطابقت ندارند',
    'password_too_short': 'رمز عبور خیلی کوتاه است',
    'password_min_length': 'رمز عبور باید حداقل ۶ کاراکتر باشد',
    'invalid_verification_code': 'کد تأیید نامعتبر',
    'account_created': 'حساب کاربری ایجاد شد!',
    'welcome_to_fooddash': 'به FoodDash خوش آمدید!',
    'registration_failed': 'ثبت نام ناموفق',
    'settings': 'تنظیمات',
    'quick_links': 'لینک‌های سریع',
    'track_order': 'ردیابی سفارش',
    'new_arrivals': 'جدیدترین‌ها',
    'customer_service': 'خدمات مشتریان',
    'help_center': 'مرکز کمک',
    'contact_us': 'تماس با ما',
    'terms_of_service': 'شرایط استفاده',
    'privacy_policy': 'سیاست حریم خصوصی',
    'refund_policy': 'سیاست بازگشت وجه',
    'for_restaurants': 'برای رستوران‌ها',
    'partner_with_us': 'با ما همکاری کنید',
    'add_your_restaurant': 'رستوران خود را اضافه کنید',
    'business_blog': 'بلاگ کسب و کار',
    'restaurant_apps': 'اپلیکیشن‌های رستوران',
    'delivery_guarantee': 'تضمین تحویل ۳۰ دقیقه‌ای',
    'secure_payments': 'پرداخت‌های امن',
    'pci_compliant': 'پرداخت‌های مطابق با PCI',
    'daily_offers': 'پیشنهادات روزانه',
    'exclusive_discounts': 'تخفیف‌های ویژه روزانه',
    'multiple_payment': 'چندین روش پرداخت',
    'all_major_cards': 'پذیرش تمام کارت‌های اصلی',
    'footer_description': 'غذاهای خوشمزه تحویل درب منزل شما. سریع، آسان و قابل اعتماد.',
    'address_kabul': 'کابل، افغانستان',
    'operating_hours': 'هر روز از ساعت ۹:۰۰ صبح تا ۱۱:۰۰ شب',
    'send_feedback': 'ارسال بازخورد',
    'feedback_description': 'ما دوست داریم از شما بشنویم! نظرات و پیشنهادات خود را به اشتراک بگذارید.',
    'your_name': 'نام شما',
    'your_email': 'ایمیل شما',
    'your_message': 'پیام شما',
    'all_rights_reserved': 'کلیه حقوق محفوظ است.',
    'designed_with_love': 'با ❤️ در افغانستان طراحی شده است',
    'my_profile': 'پروفایل من',
    'manage_delivery_locations': 'مدیریت مکان های تحویل',
    'manage_payment_options': 'مدیریت گزینه های پرداخت',
    'manage_alerts_updates': 'مدیریت هشدارها و به روزرسانی ها',
    'saved_addresses': 'آدرس های ذخیره شده',
    'add_address': 'افزودن آدرس',
    'no_saved_addresses': 'هیچ آدرسی ذخیره نشده است',
    'add_first_address': 'اولین آدرس خود را اضافه کنید',
    'default': 'پیش فرض',
    'set_default': 'تنظیم به عنوان پیش فرض',
    'delete': 'حذف',
    'confirm_delete_address': 'آیا مطمئن هستید که می خواهید این آدرس را حذف کنید؟',
    'address_deleted': 'آدرس حذف شد',
    'error_deleting_address': 'خطا در حذف آدرس',
    'default_address_updated': 'آدرس پیش فرض به روز شد',
    'error_updating_default_address': 'خطا در به روزرسانی آدرس پیش فرض',
    'sending': 'در حال ارسال...',
    // Add more translations as needed
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<string>('en');

  useEffect(() => {
    // Load language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
    
    // Set document direction based on language
    document.documentElement.lang = savedLanguage;
    document.documentElement.dir = savedLanguage === 'fa' || savedLanguage === 'ps' ? 'rtl' : 'ltr';
  }, []);

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language]?.[key] || key;
    
    // Replace parameters in the translation string
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
      
      // Handle pluralization for restaurant count
      if (key.includes('_found')) {
        const count = params.count || 0;
        // For English, we add 's' for plural, but for other languages we might not need this
        if (language === 'en') {
          translation = translation.replace('{plural}', count !== 1 ? 's' : '');
        } else {
          // For Persian and Pashto, we don't add anything for pluralization
          translation = translation.replace('{plural}', '');
        }
      }
    }
    
    return translation;
  };

  const updateLanguage = (newLanguage: string) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
    
    // Set document direction based on language
    document.documentElement.lang = newLanguage;
    document.documentElement.dir = newLanguage === 'fa' || newLanguage === 'ps' ? 'rtl' : 'ltr';
    
    // Also update the body attributes
    if (typeof document !== 'undefined') {
      document.body.setAttribute('dir', document.documentElement.dir);
      document.body.setAttribute('lang', document.documentElement.lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: updateLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}